allprojects {
    group = 'io.opentracing.contrib'
    version = '3.3.4-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'checkstyle'
    apply plugin: 'jacoco'

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    checkstyle {
        toolVersion = '8.3'
        configFile = rootProject.file('config/checkstyle/checkstyle.xml')
    }

    jacoco {
        toolVersion = '0.8.14'
    }

    dependencies {
        implementation platform('org.springframework.boot:spring-boot-dependencies:2.3.4.RELEASE')
        testImplementation platform('org.springframework.boot:spring-boot-dependencies:2.3.4.RELEASE')

        testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
        testImplementation 'org.junit.jupiter:junit-jupiter-api'
    }

    test {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            html.required = true
            csv.required = false
        }
    }
}
